import { existsSync } from "node:fs";
import { access, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { spawn } from "node:child_process";

export type ProfileSandboxSettings = { sandbox?: boolean; profile?: { skillSources?: { shared?: boolean; profile?: boolean } } };
const managedDescription = "Pi profile runtime sandbox";
export const nonoConfigPath = (profileDir: string) => join(profileDir, "nono.json");

function runtimeModulesPath(runtimeEntry: string) {
  // Covers every installed pi-node version and its trusted Node dependencies.
  return "$HOME/.local/share/pi-node/node-*";
}

function nonoPolicy(profileDir: string, runtimeEntry: string, skillSources: { shared: boolean; profile: boolean }) {
  const agentDir = dirname(dirname(profileDir));
  const pulseFiles = [join(agentDir, "pulse.db"), join(agentDir, "pulse.db-wal"), join(agentDir, "pulse.db-shm")];
  return {
    extends: "node-dev",
    meta: { name: `pi-${profileDir.split("/").pop() || "profile"}`, description: managedDescription },
    workdir: { access: "readwrite" },
    network: { network_profile: null },
    filesystem: {
      read: [
        "$HOME/.pi/agent/extensions",
        // Globally installed Pi npm packages are shared but never writable by profiles.
        "$HOME/.pi/agent/npm",
        "$HOME/.pi/agent/prompts",
        "$HOME/.pi/agent/themes",
        "$HOME/.pi/agent/guardrails",
        "$HOME/.pi/agent/AGENTS.md",
        ...(skillSources.shared ? ["$HOME/.pi/agent/skills"] : []),
        // SSH resolves the current UID through these public account maps.
        // This does not expose credentials or private keys.
        "/etc/passwd",
        "/etc/group",
        runtimeModulesPath(runtimeEntry),
        ...pulseFiles,
      ],
      // The profile directory is the sandbox workdir, so Pi can persist its
      // profile-scoped authentication, models, settings, and local state.
      allow: ["$WORKDIR", join(profileDir, "sessions"), ...(skillSources.profile ? [join(profileDir, "skills")] : []), "$TMPDIR", "/dev/pts"],
      // Allows password-driven SSH helpers (e.g. pexpect) without exposing
      // the host user's SSH keys or agent.
      allow_file: ["/dev/ptmx", ...pulseFiles],
    },
  };
}

async function run(command: string, args: string[]): Promise<void> {
  await new Promise<void>((resolveRun, reject) => {
    const child = spawn(command, args, { stdio: "ignore" });
    child.once("error", reject);
    child.once("exit", (code) => {
      if (code === 0) resolveRun();
      else reject(new Error(command + " exited with " + String(code)));
    });
  });
}

export async function ensureProfileSandbox(profileDir: string, runtimeEntry: string): Promise<string> {
  const path = nonoConfigPath(profileDir);
  let settings: ProfileSandboxSettings = {};
  try { settings = JSON.parse(await readFile(join(profileDir, "settings.json"), "utf8")) as ProfileSandboxSettings; } catch {}
  const skillSources = { shared: settings.profile?.skillSources?.shared !== false, profile: settings.profile?.skillSources?.profile === true };
  const policy = nonoPolicy(profileDir, runtimeEntry, skillSources);
  const writePolicy = async (value: unknown) => {
    const temporary = path + "." + process.pid + ".tmp";
    await writeFile(temporary, JSON.stringify(value, null, 2) + "\n", { mode: 384 });
    await rename(temporary, path);
  };
  if (!existsSync(path)) {
    await mkdir(profileDir, { recursive: true });
    await writePolicy(policy);
  } else {
    const current = JSON.parse(await readFile(path, "utf8")) as any;
    // Only migrate policies generated by us; administrator-authored policies
    // remain authoritative.
    if (current?.meta?.description === managedDescription) await writePolicy(policy);
  }
  await access(path);
  await run("nono", ["profile", "validate", path]);
  return path;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function mergeJson(persisted: unknown, legacy: unknown): unknown {
  if (!isRecord(persisted) || !isRecord(legacy)) return legacy;
  const merged: Record<string, unknown> = { ...persisted };
  for (const [key, value] of Object.entries(legacy)) merged[key] = key in merged ? mergeJson(merged[key], value) : value;
  return merged;
}

async function readJson(path: string): Promise<unknown> {
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch (error) {
    throw new Error(`could not migrate legacy sandbox state from ${path}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/** Migrates state saved by pre-direct-workdir releases, then removes .runtime. */
export async function migrateLegacySandboxRuntime(profileDir: string): Promise<void> {
  const legacyDir = join(profileDir, ".runtime");
  if (!existsSync(legacyDir)) return;
  for (const name of ["auth.json", "models.json", "models-store.json"]) {
    const legacyPath = join(legacyDir, name);
    if (!existsSync(legacyPath)) continue;
    const targetPath = join(profileDir, name);
    const merged = mergeJson(existsSync(targetPath) ? await readJson(targetPath) : {}, await readJson(legacyPath));
    const temporary = `${targetPath}.migration-${process.pid}`;
    await writeFile(temporary, `${JSON.stringify(merged, null, 2)}\n`, { mode: 0o600 });
    await rename(temporary, targetPath);
  }
  await rm(legacyDir, { recursive: true, force: true });
}

export async function isSandboxEnabled(profileDir: string, isDefault: boolean): Promise<boolean> {
  if (isDefault) return false;
  try { return (JSON.parse(await readFile(join(profileDir, "settings.json"), "utf8")) as ProfileSandboxSettings).sandbox === true; }
  catch { return false; }
}

export function sandboxedCommand(nonoProfile: string, runtimeDir: string, executable: string, args: string[]) {
  return { command: "nono", args: ["run", "--silent", "--allow-cwd", "--profile", nonoProfile, "--workdir", runtimeDir, "--", executable, ...args] };
}
