import { DatabaseSync } from "node:sqlite";
import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { cp, lstat, mkdir, readdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { existsSync, mkdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { promisify } from "node:util";
const exec = promisify(execFile), now = () => new Date().toISOString();
type Row = Record<string, unknown>;
export type Source = { identifier: string; name: string; repoUrl: string; branch: string; basePath: string; username: string | null; hasAccessToken: boolean; enabled: boolean; lastCommitHash: string | null; lastSyncedAt: string | null; syncStatus: string; lastError: string | null; createdAt: string; updatedAt: string };
const valid = (value: string) => /^[a-z][a-z0-9-]{0,63}$/.test(value);
export class SkillSourceStore {
  private db: DatabaseSync; readonly root: string; private publishing = new Map<string, Promise<unknown>>();
  constructor(agentDir: string) { this.root = join(agentDir, "skill-sources"); mkdirSync(this.root, { recursive: true }); this.db = new DatabaseSync(join(agentDir, "skill-sources.db")); this.db.exec("CREATE TABLE IF NOT EXISTS skill_sources (identifier TEXT PRIMARY KEY,name TEXT NOT NULL,repo_url TEXT NOT NULL,branch TEXT NOT NULL,base_path TEXT NOT NULL,auth_env_var TEXT,credential_username TEXT,credential_token TEXT,enabled INTEGER NOT NULL DEFAULT 1,last_commit_hash TEXT,last_synced_at TEXT,sync_status TEXT NOT NULL DEFAULT 'never_synced',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS skill_source_skills (source_identifier TEXT NOT NULL,skill_name TEXT NOT NULL,relative_path TEXT NOT NULL,description TEXT,content_hash TEXT NOT NULL,commit_hash TEXT,status TEXT NOT NULL,seen_at TEXT NOT NULL,PRIMARY KEY(source_identifier,relative_path)); CREATE TABLE IF NOT EXISTS skill_source_sync_runs (id TEXT PRIMARY KEY,source_identifier TEXT NOT NULL,status TEXT NOT NULL,commit_hash TEXT,discovered_count INTEGER NOT NULL,valid_count INTEGER NOT NULL,invalid_count INTEGER NOT NULL,error_summary TEXT,started_at TEXT NOT NULL,finished_at TEXT); CREATE TABLE IF NOT EXISTS skill_source_installations (profile TEXT NOT NULL,skill_name TEXT NOT NULL,source_identifier TEXT NOT NULL,source_relative_path TEXT NOT NULL,source_commit_hash TEXT,source_content_hash TEXT NOT NULL,target_path TEXT NOT NULL,installed_at TEXT NOT NULL,PRIMARY KEY(profile,skill_name))"); const skillSql = String((this.db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='skill_source_skills'").get() as Row | undefined)?.sql ?? ""); if (skillSql.includes("PRIMARY KEY(source_identifier,skill_name)")) this.db.exec("BEGIN; ALTER TABLE skill_source_skills RENAME TO skill_source_skills_legacy; CREATE TABLE skill_source_skills (source_identifier TEXT NOT NULL,skill_name TEXT NOT NULL,relative_path TEXT NOT NULL,description TEXT,content_hash TEXT NOT NULL,commit_hash TEXT,status TEXT NOT NULL,seen_at TEXT NOT NULL,PRIMARY KEY(source_identifier,relative_path)); INSERT INTO skill_source_skills SELECT source_identifier,skill_name,relative_path,description,content_hash,commit_hash,status,seen_at FROM skill_source_skills_legacy; DROP TABLE skill_source_skills_legacy; COMMIT;"); const columns = new Set((this.db.prepare("PRAGMA table_info(skill_sources)").all() as Row[]).map(row => String(row.name))); if (!columns.has("credential_username")) this.db.exec("ALTER TABLE skill_sources ADD COLUMN credential_username TEXT"); if (!columns.has("credential_token")) this.db.exec("ALTER TABLE skill_sources ADD COLUMN credential_token TEXT"); }
  private source(row: Row): Source { return { identifier:String(row.identifier), name:String(row.name), repoUrl:String(row.repo_url), branch:String(row.branch), basePath:String(row.base_path), username:row.credential_username == null ? null : String(row.credential_username), hasAccessToken:Boolean(row.credential_token), enabled:Boolean(row.enabled), lastCommitHash:row.last_commit_hash == null ? null : String(row.last_commit_hash), lastSyncedAt:row.last_synced_at == null ? null : String(row.last_synced_at), syncStatus:String(row.sync_status), lastError:row.last_error == null ? null : String(row.last_error), createdAt:String(row.created_at), updatedAt:String(row.updated_at) }; }
  list() { return (this.db.prepare("SELECT * FROM skill_sources ORDER BY name").all() as Row[]).map(row => this.source(row)); }
  get(identifier: string) { const row = this.db.prepare("SELECT * FROM skill_sources WHERE identifier=?").get(identifier) as Row | undefined; return row ? this.source(row) : undefined; }
  save(input: Partial<Source> & { identifier: string; name: string; repoUrl: string; accessToken?: string }) { if (!valid(input.identifier)) throw Object.assign(new Error("Identifier must start with a lowercase letter and contain only lowercase letters, numbers or hyphens."), { status: 400 }); if (!input.name.trim() || !input.repoUrl.trim()) throw Object.assign(new Error("Name and repository URL are required."), { status: 400 }); const current=this.get(input.identifier), stamp=now(), branch=input.branch?.trim() || current?.branch || "main", basePath=(input.basePath?.trim() || current?.basePath || "skills").replace(/^\/+|\/+$/g, ""); if (!basePath || basePath.split("/").includes("..")) throw Object.assign(new Error("Invalid base path."), { status: 400 }); if (current) this.db.prepare("UPDATE skill_sources SET name=?,repo_url=?,branch=?,base_path=?,credential_username=?,credential_token=CASE WHEN ? THEN ? ELSE credential_token END,enabled=?,updated_at=? WHERE identifier=?").run(input.name.trim(),input.repoUrl.trim(),branch,basePath,input.username?.trim() || null,input.accessToken !== undefined ? 1 : 0,input.accessToken?.trim() || null,input.enabled === false ? 0 : 1,stamp,input.identifier); else this.db.prepare("INSERT INTO skill_sources (identifier,name,repo_url,branch,base_path,credential_username,credential_token,enabled,last_commit_hash,last_synced_at,sync_status,last_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(input.identifier,input.name.trim(),input.repoUrl.trim(),branch,basePath,input.username?.trim() || null,input.accessToken?.trim() || null,input.enabled === false ? 0 : 1,null,null,"never_synced",null,stamp,stamp); return this.get(input.identifier)!; }
  async rename(identifier: string, nextIdentifier: string) { if (identifier === nextIdentifier) return; if (!valid(nextIdentifier)) throw Object.assign(new Error("Identifier must start with a lowercase letter and contain only lowercase letters, numbers or hyphens."), { status: 400 }); if (!this.get(identifier)) throw Object.assign(new Error("Skill Source not found."), { status: 404 }); if (this.get(nextIdentifier)) throw Object.assign(new Error("A Skill Source with this identifier already exists."), { status: 409 }); const previous=join(this.root,identifier), next=join(this.root,nextIdentifier), cachePrevious=join(this.root,".git-cache",identifier), cacheNext=join(this.root,".git-cache",nextIdentifier); if (existsSync(previous)) await rename(previous,next); if (existsSync(cachePrevious)) await rename(cachePrevious,cacheNext); this.db.exec("BEGIN"); try { for (const table of ["skill_sources","skill_source_skills","skill_source_sync_runs","skill_source_installations"]) this.db.prepare(`UPDATE ${table} SET ${table === "skill_sources" ? "identifier" : "source_identifier"}=? WHERE ${table === "skill_sources" ? "identifier" : "source_identifier"}=?`).run(nextIdentifier,identifier); this.db.exec("COMMIT"); } catch(error) { this.db.exec("ROLLBACK"); if (existsSync(next) && !existsSync(previous)) await rename(next,previous); if (existsSync(cacheNext) && !existsSync(cachePrevious)) await rename(cacheNext,cachePrevious); throw error; } }
  async remove(identifier: string) { if (!this.get(identifier)) throw Object.assign(new Error("Skill Source not found."), { status: 404 }); this.db.prepare("DELETE FROM skill_source_skills WHERE source_identifier=?").run(identifier); this.db.prepare("DELETE FROM skill_sources WHERE identifier=?").run(identifier); await rm(join(this.root, identifier), { recursive:true, force:true }); await rm(join(this.root, ".git-cache", identifier), { recursive:true, force:true }); }
  skills(identifier: string) { if (!this.get(identifier)) throw Object.assign(new Error("Skill Source not found."), { status:404 }); return (this.db.prepare("SELECT skill_name,relative_path,description,content_hash,commit_hash,status,seen_at FROM skill_source_skills WHERE source_identifier=? ORDER BY skill_name").all(identifier) as Row[]).map(row => ({ name:String(row.skill_name), relativePath:String(row.relative_path), description:row.description == null ? null : String(row.description), contentHash:String(row.content_hash), commitHash:row.commit_hash == null ? null : String(row.commit_hash), status:String(row.status), seenAt:String(row.seen_at) })); }
  async document(identifier: string, skillName: string) { const skill=this.skills(identifier).find(item=>item.name===skillName && item.status === "synced"); if (!skill) throw Object.assign(new Error("Skill document is not available."), { status: 404 }); const root=resolve(this.root,identifier), folder=resolve(root,skill.relativePath), path=join(folder,"SKILL.md"); if (!folder.startsWith(`${root}/`) || !existsSync(path)) throw Object.assign(new Error("Skill document is not available."), { status: 404 }); const raw=await readFile(path,"utf8"), match=raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/), frontmatter:Record<string,string>={}; if (match) for (const line of match[1].split(/\r?\n/)) { const separator=line.indexOf(":"); if (separator > 0) frontmatter[line.slice(0,separator).trim()]=line.slice(separator+1).trim().replace(/^['\"]|['\"]$/g,""); } const source=this.get(identifier)!; return { name:skill.name,path:relative(root,path).replaceAll("\\","/"),frontmatter,content:match ? raw.slice(match[0].length) : raw,source:{identifier:source.identifier,name:source.name,commitHash:skill.commitHash} }; }
  private async git(args: string[], cwd: string, env: NodeJS.ProcessEnv) { try { return (await exec("git", args, { cwd, env, timeout:120000, maxBuffer:1024*1024 })).stdout.trim(); } catch (error) { const text=String((error as { stderr?: string }).stderr ?? (error as Error).message).replace(/https?:\/\/[^@\s]+@/g,"https://***@").slice(0,800); throw new Error(text || "Git command failed."); } }
  private async scan(base: string, repo: string, commit: string) { const found: Array<{name:string;relativePath:string;description:string|null;contentHash:string}> = []; const visit=async (dir:string):Promise<void> => { for (const entry of await readdir(dir,{withFileTypes:true})) { if (!entry.isDirectory() || entry.name === ".git") continue; const folder=join(dir,entry.name), file=join(folder,"SKILL.md"); if (existsSync(file)) { const content=await readFile(file,"utf8"), front=content.match(/^---\r?\n([\s\S]*?)\r?\n---/), name=front?.[1].match(/^name:\s*["']?([^\n"']+)/m)?.[1].trim() || relative(base,folder).replaceAll("\\","/"), description=front?.[1].match(/^description:\s*["']?([^\n"']+)/m)?.[1].trim() || null; found.push({name,relativePath:relative(repo,folder).replaceAll("\\","/"),description,contentHash:createHash("sha256").update(content).digest("hex")}); } else await visit(folder); } }; await visit(base); return found; }
  async sync(identifier: string) { const source=this.get(identifier); if (!source) throw Object.assign(new Error("Skill Source not found."), { status:404 }); if (!source.enabled) throw Object.assign(new Error("Skill Source is disabled."), { status:422 }); const started=now(), run=randomUUID(), repo=join(this.root,".git-cache",identifier), destination=join(this.root,identifier), env:{[key:string]:string|undefined}={...process.env,GIT_TERMINAL_PROMPT:"0"}; let askpass: string | undefined; const tokenRow=this.db.prepare("SELECT credential_token FROM skill_sources WHERE identifier=?").get(identifier) as Row | undefined; const token=tokenRow?.credential_token == null ? undefined : String(tokenRow.credential_token); if (token) { askpass=join(this.root,`.git-askpass-${run}`); await writeFile(askpass,"#!/bin/sh\ncase \"$1\" in *Username*) printf '%s\\n' \"$PI_SKILL_SOURCE_GIT_USERNAME\" ;; *Password*) printf '%s\\n' \"$PI_SKILL_SOURCE_GIT_TOKEN\" ;; esac\n",{mode:0o700}); Object.assign(env,{GIT_ASKPASS:askpass,PI_SKILL_SOURCE_GIT_USERNAME:source.username || "x-access-token",PI_SKILL_SOURCE_GIT_TOKEN:token}); }
    this.db.prepare("INSERT INTO skill_source_sync_runs VALUES (?,?,?,?,?,?,?,?,?,?)").run(run,identifier,"running",null,0,0,0,null,started,null); let commit:string|null=null, items:Awaited<ReturnType<SkillSourceStore["scan"]>>=[]; let error:string|null=null; try { if (!existsSync(join(repo,".git"))) { await rm(repo,{recursive:true,force:true}); await mkdir(dirname(repo),{recursive:true}); await this.git(["clone","--depth","1","--branch",source.branch,source.repoUrl,repo],this.root,env); } else { await this.git(["remote","set-url","origin",source.repoUrl],repo,env); await this.git(["fetch","--depth","1","--prune","origin",source.branch],repo,env); await this.git(["checkout","--force","-B",source.branch,`origin/${source.branch}`],repo,env); await this.git(["clean","-ffd"],repo,env); } commit=await this.git(["rev-parse","HEAD"],repo,env); const base=resolve(repo,source.basePath); if (!base.startsWith(`${resolve(repo)}/`) || !existsSync(base) || !(await stat(base)).isDirectory()) throw new Error(`Skill base path was not found: ${source.basePath}`); await rm(destination,{recursive:true,force:true}); await cp(base,destination,{recursive:true,filter:(path)=>!path.split("/").includes(".git")}); items=await this.scan(destination,destination,commit); const stamp=now(); this.db.prepare("UPDATE skill_source_skills SET status='missing' WHERE source_identifier=?").run(identifier); for (const item of items) this.db.prepare("INSERT INTO skill_source_skills VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(source_identifier,relative_path) DO UPDATE SET skill_name=excluded.skill_name,description=excluded.description,content_hash=excluded.content_hash,commit_hash=excluded.commit_hash,status='synced',seen_at=excluded.seen_at").run(identifier,item.name,item.relativePath,item.description,item.contentHash,commit,"synced",stamp); } catch (cause) { error=(cause as Error).message; }
    if (askpass) await rm(askpass,{force:true}); const status=error ? (items.length ? "partial_failure" : "failed") : "succeeded", finished=now(); this.db.prepare("UPDATE skill_sources SET last_commit_hash=?,last_synced_at=?,sync_status=?,last_error=?,updated_at=? WHERE identifier=?").run(commit,finished,status,error,finished,identifier); this.db.prepare("UPDATE skill_source_sync_runs SET status=?,commit_hash=?,discovered_count=?,valid_count=?,invalid_count=?,error_summary=?,finished_at=? WHERE id=?").run(status,commit,items.length,items.length,0,error,finished,run); return { source:this.get(identifier)!, status, commitHash:commit, discoveredCount:items.length, validCount:items.length, invalidCount:0, error }; }
  private async validateSkillDirectory(directory: string): Promise<void> {
    const root = resolve(directory);
    const visit = async (path: string): Promise<void> => {
      const entry = await lstat(path);
      if (entry.isSymbolicLink()) throw Object.assign(new Error("Skills containing symbolic links cannot be published."), { status: 400 });
      if (!entry.isDirectory()) return;
      for (const child of await readdir(path)) await visit(join(path, child));
    };
    await visit(root);
    if (!existsSync(join(root, "SKILL.md"))) throw Object.assign(new Error("The skill directory does not contain SKILL.md."), { status: 400 });
  }

  private installation(profile: string, skillName: string) {
    return this.db.prepare("SELECT source_identifier,source_relative_path,target_path FROM skill_source_installations WHERE profile=? AND skill_name=?").get(profile, skillName) as Row | undefined;
  }

  async publish(identifier: string, profile: string, skillName: string, skillPath: string) {
    const previous = this.publishing.get(identifier) ?? Promise.resolve();
    let release!: () => void;
    const queued = new Promise<void>((resolveRun) => { release = resolveRun; });
    const chain = previous.then(() => queued);
    this.publishing.set(identifier, chain);
    await previous;
    try {
      const source = this.get(identifier);
      if (!source) throw Object.assign(new Error("Skill Source not found."), { status: 404 });
      if (!source.enabled) throw Object.assign(new Error("Skill Source is disabled."), { status: 422 });
      if (!source.hasAccessToken) throw Object.assign(new Error("This Skill Source has no write credential."), { status: 422 });
      const local = resolve(skillPath);
      await this.validateSkillDirectory(local);
      const installation = this.installation(profile, skillName);
      if (installation && String(installation.source_identifier) !== identifier) throw Object.assign(new Error("This skill was imported from a different Skill Source. Publish it there or create a new local skill."), { status: 409 });
      const targetRelative = installation ? String(installation.source_relative_path) : join(source.basePath, skillName).replaceAll("\\", "/");
      if (targetRelative.split("/").includes("..") || targetRelative.startsWith("/")) throw Object.assign(new Error("Invalid skill destination."), { status: 400 });
      const sameName = this.skills(identifier).filter((item) => item.name === skillName && item.relativePath !== targetRelative && item.status === "synced");
      if (sameName.length) throw Object.assign(new Error(`A different skill named '${skillName}' already exists in this Skill Source. Publish by its original path or rename the local skill.`), { status: 409 });
      const refreshed = await this.sync(identifier);
      if (refreshed.status !== "succeeded") throw Object.assign(new Error(refreshed.error ?? "Unable to synchronize the Skill Source before publishing."), { status: 502 });
      const repository = resolve(this.root, ".git-cache", identifier), target = resolve(repository, targetRelative);
      if (!target.startsWith(`${repository}/`)) throw Object.assign(new Error("Invalid skill destination."), { status: 400 });
      await rm(target, { recursive: true, force: true });
      await mkdir(dirname(target), { recursive: true });
      await cp(local, target, { recursive: true, filter: (path) => !path.split("/").includes("node_modules") && !path.split("/").includes(".git") });
      const token = String((this.db.prepare("SELECT credential_token FROM skill_sources WHERE identifier=?").get(identifier) as Row).credential_token);
      const askpass = join(this.root, `.git-askpass-publish-${randomUUID()}`), env: NodeJS.ProcessEnv = { ...process.env, GIT_TERMINAL_PROMPT: "0", GIT_ASKPASS: askpass, PI_SKILL_SOURCE_GIT_USERNAME: source.username || "x-access-token", PI_SKILL_SOURCE_GIT_TOKEN: token };
      await writeFile(askpass, "#!/bin/sh\ncase \"$1\" in *Username*) printf '%s\\n' \"$PI_SKILL_SOURCE_GIT_USERNAME\" ;; *Password*) printf '%s\\n' \"$PI_SKILL_SOURCE_GIT_TOKEN\" ;; esac\n", { mode: 0o700 });
      try {
        await this.git(["add", "--", targetRelative], repository, env);
        const status = await this.git(["status", "--porcelain", "--", targetRelative], repository, env);
        if (!status) return { action: "unchanged" as const, source: identifier, relativePath: targetRelative, commitHash: refreshed.commitHash };
        await this.git(["commit", "-m", `chore(skills): update ${skillName}`], repository, env);
        await this.git(["push", "origin", source.branch], repository, env);
      } finally { await rm(askpass, { force: true }); }
      const synced = await this.sync(identifier);
      if (synced.status !== "succeeded") throw Object.assign(new Error(synced.error ?? "The Skill Source was pushed but could not be synchronized."), { status: 502 });
      const published = this.skills(identifier).find((item) => item.relativePath === targetRelative);
      if (published) this.db.prepare("INSERT INTO skill_source_installations VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(profile,skill_name) DO UPDATE SET source_identifier=excluded.source_identifier,source_relative_path=excluded.source_relative_path,source_commit_hash=excluded.source_commit_hash,source_content_hash=excluded.source_content_hash,target_path=excluded.target_path,installed_at=excluded.installed_at").run(profile,skillName,identifier,targetRelative,published.commitHash,published.contentHash,local,now());
      return { action: installation ? "updated" as const : "created" as const, source: identifier, relativePath: targetRelative, commitHash: synced.commitHash };
    } finally { release(); if (this.publishing.get(identifier) === chain) this.publishing.delete(identifier); }
  }

  async syncInstallation(profile: string, skillName: string, expectedPath: string) {
    const installation = this.installation(profile, skillName);
    if (!installation) throw Object.assign(new Error("This Skill was not installed from a Skill Source."), { status: 404 });
    const identifier = String(installation.source_identifier), relativePath = String(installation.source_relative_path), target = resolve(String(installation.target_path));
    if (target !== resolve(expectedPath)) throw Object.assign(new Error("The installed Skill path no longer matches its source record."), { status: 409 });
    const result = await this.sync(identifier);
    if (result.status !== "succeeded") throw Object.assign(new Error(result.error ?? "Unable to synchronize the Skill Source."), { status: 502 });
    const skill = this.skills(identifier).find((item) => item.relativePath === relativePath && item.status === "synced");
    if (!skill) throw Object.assign(new Error("This Skill no longer exists in its Skill Source."), { status: 404 });
    const sourceRoot = resolve(this.root, identifier), source = resolve(sourceRoot, relativePath);
    if (!source.startsWith(`${sourceRoot}/`) || !existsSync(join(source, "SKILL.md"))) throw Object.assign(new Error("The synchronized Skill files are unavailable."), { status: 404 });
    const temporary = `${target}.sync-${randomUUID()}`, backup = `${target}.backup-${randomUUID()}`;
    try {
      await rm(temporary, { recursive: true, force: true });
      await cp(source, temporary, { recursive: true, filter: (path) => !path.split("/").includes(".git") && !path.split("/").includes("node_modules") });
      if (existsSync(target)) await rename(target, backup);
      await rename(temporary, target);
      await rm(backup, { recursive: true, force: true });
    } catch (error) {
      await rm(temporary, { recursive: true, force: true });
      if (!existsSync(target) && existsSync(backup)) await rename(backup, target);
      throw error;
    }
    this.db.prepare("UPDATE skill_source_installations SET source_commit_hash=?,source_content_hash=?,target_path=?,installed_at=? WHERE profile=? AND skill_name=?").run(skill.commitHash, skill.contentHash, target, now(), profile, skillName);
    return { source: identifier, relativePath, commitHash: skill.commitHash };
  }

  forgetInstallation(profile: string, skillName: string) { this.db.prepare("DELETE FROM skill_source_installations WHERE profile=? AND skill_name=?").run(profile, skillName); }
  async install(identifier:string, skillName:string, destination:string, profile:string) { const skill=this.skills(identifier).find(item=>item.name===skillName && item.status==="synced"); if (!skill) throw Object.assign(new Error("Skill was not found in the synchronized source."),{status:404}); const source=resolve(this.root,identifier,skill.relativePath), target=resolve(destination,skillName); if (!source.startsWith(`${resolve(this.root,identifier)}/`) || !target.startsWith(`${resolve(destination)}/`)) throw Object.assign(new Error("Invalid skill path."),{status:400}); if (existsSync(target)) throw Object.assign(new Error("A skill with this name already exists at the destination."),{status:409}); await mkdir(destination,{recursive:true}); await cp(source,target,{recursive:true,filter:(path)=>!path.split("/").includes(".git") && !path.split("/").includes("node_modules")}); this.db.prepare("INSERT INTO skill_source_installations VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(profile,skill_name) DO UPDATE SET source_identifier=excluded.source_identifier,source_relative_path=excluded.source_relative_path,source_commit_hash=excluded.source_commit_hash,source_content_hash=excluded.source_content_hash,target_path=excluded.target_path,installed_at=excluded.installed_at").run(profile,skill.name,identifier,skill.relativePath,skill.commitHash,skill.contentHash,target,now()); return skill; }
}
