"use client";
import { useState } from "react";
import { Loader2, RotateCw, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/toast";

type Target = "api-server" | "pi-console-webui";
export function AdminConfigForm({ target, initial }: { target: Target; initial?: Record<string, unknown> }) {
  const { toast } = useToast(); const api = target === "api-server";
  const [host, setHost] = useState(String(initial?.host ?? (api ? "0.0.0.0" : "127.0.0.1"))); const [port, setPort] = useState(String(initial?.port ?? (api ? 8767 : 3030))); const [username, setUsername] = useState(String(initial?.username ?? "admin")); const [password, setPassword] = useState(String(initial?.password ?? "")); const [secret, setSecret] = useState(String(initial?.secret ?? "")); const [corsOrigin, setCorsOrigin] = useState(String((initial?.cors as { origin?: string } | undefined)?.origin ?? "*")); const [apiToken, setApiToken] = useState(""); const [saving, setSaving] = useState(false), [restarting, setRestarting] = useState(false);
  const save = async () => { if (saving) return; try { setSaving(true); const config: Record<string, unknown> = api ? { host, port: Number(port), cors: { origin: corsOrigin } } : { host, port: Number(port), username, password, secret }; if (apiToken) config.apiToken = apiToken; const response = await fetch(`/api/admin/config/${target}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(config) }); if (!response.ok) throw new Error((await response.json()).error ?? "Unable to save configuration"); toast("Configuration saved."); } catch (cause) { toast((cause as Error).message, "error"); } finally { setSaving(false); } };
  const restart = async () => { if (restarting) return; try { setRestarting(true); const response = await fetch(`/api/admin/services/${target}/restart`, { method: "POST" }); if (!response.ok) throw new Error("Unable to restart service"); toast("Service restart requested."); } catch (cause) { toast((cause as Error).message, "error"); } finally { setRestarting(false); } };
  return <Card><div className="flex items-center justify-between gap-3"><div><CardTitle>{api ? "API Server" : "Pi Console WebUI"}</CardTitle><p className="text-sm text-zinc-500">Update service settings and restart to apply changes.</p></div><div className="flex gap-2"><Button className="bg-zinc-100 text-zinc-700 hover:bg-zinc-200" title="Restart service" disabled={restarting} onClick={restart}>{restarting ? <Loader2 className="animate-spin" size={17}/> : <RotateCw size={17}/>}</Button><Button className="!bg-[#2bbb77] hover:!bg-[#249b63]" title="Save configuration" disabled={saving} onClick={save}>{saving ? <Loader2 className="animate-spin" size={17}/> : <Save size={17}/>}</Button></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Host<Input className="mt-1" value={host} onChange={(event) => setHost(event.target.value)}/></label><label className="text-sm font-medium">Port<Input className="mt-1" type="number" min="1" max="65535" value={port} onChange={(event) => setPort(event.target.value)}/></label>{api ? <><label className="text-sm font-medium md:col-span-2">CORS origin<Input className="mt-1" value={corsOrigin} onChange={(event) => setCorsOrigin(event.target.value)}/></label><label className="text-sm font-medium md:col-span-2">Replace API token <span className="font-normal text-zinc-500">(leave blank to keep current token)</span><Input className="mt-1" type="password" value={apiToken} onChange={(event) => setApiToken(event.target.value)} placeholder="New API token"/></label></> : <><label className="text-sm font-medium">Username<Input className="mt-1" value={username} onChange={(event) => setUsername(event.target.value)}/></label><label className="text-sm font-medium">Password<Input className="mt-1" type="password" value={password} onChange={(event) => setPassword(event.target.value)}/></label><label className="text-sm font-medium md:col-span-2">Session secret<Input className="mt-1" value={secret} onChange={(event) => setSecret(event.target.value)}/></label></>}</div></Card>;
}
