"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Copy, Plus, Trash2, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { useToast } from "@/components/toast";
type Application = { name: string; slug: string; enabled: boolean; responseMode: string; defaultProfile: string | null };
const api = async (path: string, init?: RequestInit) => { const response = await fetch(`/api/pi/${path}`, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error?.message ?? "Request failed"); return response.json(); };
export function Applications() {
  const { toast } = useToast(); const [items, setItems] = useState<Application[]>([]), [error, setError] = useState("");
  useEffect(() => { api("applications").then((data) => setItems(data.applications)).catch((cause) => setError(cause.message)); }, []);
  const remove = async (value: Application) => { if (!confirm(`Delete Application '${value.name}'? Its handlers and logs will be deleted.`)) return; try { await api(`applications/${encodeURIComponent(value.slug)}`, { method: "DELETE" }); setItems((current) => current.filter((item) => item.slug !== value.slug)); } catch (cause) { setError((cause as Error).message); } };
  return <Card><div className="flex items-center justify-between gap-3"><div><CardTitle>Applications</CardTitle><p className="mt-1 text-sm text-zinc-500">Independent public endpoints and Pi message pipelines.</p></div><Link href="/applications/new?context=admin"><Button title="Create Application"><Plus size={17}/></Button></Link></div>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-zinc-500"><tr><th className="p-3">Name</th><th className="p-3">Slug</th><th className="p-3">Profile</th><th className="p-3">Mode</th><th className="p-3">Status</th><th className="p-3"/></tr></thead><tbody>{items.map((item) => <tr key={item.slug} className="border-b border-zinc-100"><td className="p-3 font-medium">{item.name}</td><td className="p-3 font-mono text-zinc-500">{item.slug}</td><td className="p-3">{item.defaultProfile ?? "—"}</td><td className="p-3">{item.responseMode}</td><td className="p-3">{item.enabled ? "Enabled" : "Disabled"}</td><td className="p-3"><div className="flex gap-1"><Link href={`/applications/${encodeURIComponent(item.slug)}?context=admin`}><Button className="bg-zinc-100 text-zinc-700 hover:bg-zinc-200" title="Manage"><Wrench size={16}/></Button></Link><Button className="bg-zinc-100 text-zinc-700 hover:bg-zinc-200" title="Copy endpoint" onClick={() => navigator.clipboard.writeText(`${location.origin}/api/message/app/${item.slug}`).then(() => toast("Endpoint copied."))}><Copy size={16}/></Button><Button className="bg-zinc-100 text-zinc-700 hover:bg-red-50 hover:text-red-700" title="Delete" onClick={() => remove(item)}><Trash2 size={16}/></Button></div></td></tr>)}{!items.length && <tr><td colSpan={6} className="p-6 text-center text-zinc-500">No Applications configured.</td></tr>}</tbody></table></div></Card>;
}
